version: '3.8'

services:
  app:
    build: .
    container_name: edustack-auth
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app 
      - /app/node_modules
    restart: unless-stopped
   